spring.datasource.url=${PROD_DATABASE_URL}
spring.datasource.username=${PROD_USERNAME}
spring.datasource.password=${PROD_PASSWORD}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://kinoxp.mbserv.dk}